<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="2.81s"
		durationms="2811"
		type="root"
		rid="4b21f1ae03c6c3d"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="erdogb"
		rxversion="8.1.1.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="06.09.2018 10:43:06"
		timestampiso="2018-09-06T08:43:06"
		endtime="06.09.2018 10:43:09"
		timeoutfactor="1"
		module="AcknowledgeDeviation">
		<detail>
			AcknowledgeDeviation
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:02.810"
			timeRelativeToTestModuleStartTime="00:02.810"
			timeWallClock="10:43:09"
			time="00:02.810"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
