<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="12.11s"
		durationms="12114"
		type="root"
		rid="7de6f0ca20130a2"
		totalerrorcount="2"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="erdogb"
		rxversion="8.1.1.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="07.05.2018 10:59:59"
		timestampiso="2018-05-07T08:59:59"
		endtime="07.05.2018 11:00:11"
		timeoutfactor="1"
		module="loginUser">
		<detail>
			loginUser
		</detail>
		<errormessage>
			No element found for path '/form[@title~'^http://192\.168\.250\.183/el']' within 10s.
		</errormessage>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:12.114"
			timeRelativeToTestModuleStartTime="00:12.115"
			timeWallClock="11:00:11"
			time="00:12.114"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:12.114"
			timeRelativeToTestModuleStartTime="00:12.115"
			timeWallClock="11:00:11"
			time="00:12.114"
			level="Error"
			category="Module"
			errimg=".\loginUse_5b90d426_c3032dbe_trace.jpg"
			errthumb=".\loginUse_5b90d426_c3032dbe_trace_thumb.jpg">
			<message>
				No element found for path '/form[@title~'^http://192\.168\.250\.183/el']' within 10s.
			</message>
			<metainfo
				stacktrace="   bei Ranorex.Core.Element.FindSingle(RxPath path, Duration timeout)
   bei Ranorex.Core.Element.FromPath(String path)
   bei Ranorex.Form.FromPath(String path)
   bei Ranorex.Form.op_Implicit(String path)
   bei smokeTest.loginUser.Ranorex.Core.Testing.ITestModule.Run() in c:\Users\erdogb\Documents\Ranorex\RanorexStudio Projects\smokeTest\smokeTest\loginUser.cs:Zeile 51.
   bei Ranorex.Core.Testing.TestModuleLeaf.RunInternal(DataContext parentDataContext, Int32 iteration, Int32 iterationCount, Boolean skipIteration)"
				codefile="c:\Users\erdogb\Documents\Ranorex\RanorexStudio Projects\smokeTest\smokeTest\loginUser.cs"
				codeline="51"
				loglvl="Error">
			</metainfo>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:12.136"
			timeRelativeToTestModuleStartTime="00:12.137"
			timeWallClock="11:00:11"
			time="00:12.136"
			level="Failure"
			category="Module"
			errimg=".\loginUse_5b90d426_c3032dbe_trace.jpg"
			errthumb=".\loginUse_5b90d426_c3032dbe_trace_thumb.jpg">
			<message>
				Der Thread wurde abgebrochen.
			</message>
			<metainfo
				stacktrace="   bei System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   bei System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   bei System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   bei Ranorex.Core.Reporting.TestReport.SaveLocalScreenshotBuffer(Activity mod)
   bei Ranorex.Core.Testing.TestModuleRunner.TrySaveModuleScreenshots()
   bei Ranorex.Core.Testing.TestModuleRunner.RunStandalone(ITestModule module, String reportFilename, Boolean generateReport, String standaloneModuleName, CaseInsensitiveString guid)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
