<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="22e5fdcb32a4996c"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="2"
		totalblockedtestcasecount="1"
		childsuccesscount="1"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="2"
		totalblockedcount="1"
		user="erdogb"
		rxversion="7.2.0.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="24.04.2018 08:27:37"
		timestampiso="2018-04-24T06:27:37"
		endtime="24.04.2018 08:27:48"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Success"
			duration="11.04s"
			durationms="11041"
			type="test-suite"
			rid="ad14461bd990956"
			totalerrorcount="1"
			totalwarningcount="0"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="2"
			totalblockedtestcasecount="1"
			childsuccesscount="0"
			childfailedcount="2"
			childblockedcount="1"
			totalsuccesscount="0"
			totalfailedcount="2"
			totalblockedcount="1"
			testsuitename="smokeTest"
			headertext="smokeTest"
			runconfigname="SmokeTest_TR_1"
			runlabel="">
			<params>
			</params>
			<errormessage>
				An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Der Thread wurde abgebrochen.
   bei Ranorex.Core.Testing.TestCaseNode.TryLoadDataFromSource()
   bei Ranorex.Core.Testing.TestCaseNode.RunInternal(Boolean childSkip)
   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
			</errormessage>
			<activity
				result="Failed"
				duration="10.33s"
				durationms="10331"
				type="test-case"
				rid="43c7d4cff27f9b0"
				totalerrorcount="1"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="1"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(OpenApp&amp;Login)"
				testcontainerid="61937f4c-9161-4e1c-9d17-78d25c90eb40"
				headertext="TestCase(OpenApp&amp;Login)"
				displayName="TestCase(OpenApp&amp;Login)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
				<activity
					result="Failed"
					duration="10.32s"
					durationms="10316"
					type="test-module"
					rid="16acc6a285ee4cb8"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					modulename="logIn"
					displayName="logIn"
					moduleid="0fd8dafe-0fee-4dde-842c-5ab594e9145c"
					moduletype="UserCode"
					iteration="1"
					activity-exectype="execute"
					testentry-activity-type="testmodule">
					<varbindings>
					</varbindings>
					<item
						timeRelativeToTestSuiteStartTime="00:10.453"
						timeRelativeToTestModuleStartTime="00:10.233"
						timeWallClock="08:27:48"
						time="00:10.453"
						level="Error"
						category="User"
						errimg="images_smokeTes_b06a1460\smokeTes_b06a1460_b9aec10c_trace.jpg"
						errthumb="images_smokeTes_b06a1460\smokeTes_b06a1460_b9aec10c_trace_thumb.jpg">
						<message>
							The test run has been aborted by the user.
						</message>
						<metainfo
							loglvl="Error">
						</metainfo>
					</item>
				</activity>
			</activity>
			<activity
				result="Ignored"
				duration="1ms"
				durationms="1"
				type="test-case"
				rid="3cee9f8d1ab4038"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="0"
				totalblockedtestcasecount="1"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="0"
				totalblockedcount="1"
				testcontainername="TestCase(Verification)"
				testcontainerid="f2a26f24-7c5b-403e-9be6-dd76f8db12ea"
				headertext="TestCase(Verification)"
				displayName="TestCase(Verification)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
			</activity>
			<activity
				result="Failed"
				duration="1ms"
				durationms="1"
				type="test-case"
				rid="1e516e5a5dadbd98"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(addProModuls)"
				testcontainerid="d37a3e0e-f52b-437d-b7a5-9a13fd40e949"
				headertext="TestCase(addProModuls)"
				displayName="TestCase(addProModuls)"
				iteration="0"
				activity-exectype="execute"
				conditionstate="none">
				<errormessage>
					Failed to get rows from data source: Failed to load Excel data. Der Thread wurde abgebrochen.
				</errormessage>
			</activity>
		</activity>
		<item
			timeRelativeToTestSuiteStartTime="00:11.238"
			timeRelativeToTestModuleStartTime="00:11.239"
			timeWallClock="08:27:48"
			time="00:11.238"
			level="Failure"
			category="TestSuite">
			<message>
				Der Thread wurde abgebrochen.
			</message>
			<metainfo
				stacktrace="   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)&#13;&#10;   bei Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.TryRunTestSuite(RunParams rp, TestSuite testSuite)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.&lt;>c__DisplayClass8_1.&lt;RunInternal>b__1()&#13;&#10;   bei Ranorex.Common.Types.OptCombinators.UnwrapOrElse[T](Opt`1 self, Func`1 generator)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
