<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="13d17aaea389d80"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="2"
		totalblockedtestcasecount="1"
		childsuccesscount="1"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="2"
		totalblockedcount="1"
		user="erdogb"
		rxversion="7.2.0.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="20.04.2018 10:05:16"
		timestampiso="2018-04-20T08:05:16"
		endtime="20.04.2018 10:05:29"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Success"
			duration="12.75s"
			durationms="12752"
			type="test-suite"
			rid="344ca9c5cc45da35"
			totalerrorcount="1"
			totalwarningcount="0"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="2"
			totalblockedtestcasecount="1"
			childsuccesscount="0"
			childfailedcount="2"
			childblockedcount="1"
			totalsuccesscount="0"
			totalfailedcount="2"
			totalblockedcount="1"
			testsuitename="smokeTest"
			headertext="smokeTest"
			runconfigname="SmokeTest_TR_2"
			runlabel="">
			<params>
			</params>
			<errormessage>
				An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Der Thread wurde abgebrochen.
   bei Ranorex.Core.Testing.TestCaseNode.TryLoadDataFromSource()
   bei Ranorex.Core.Testing.TestCaseNode.RunInternal(Boolean childSkip)
   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
			</errormessage>
			<activity
				result="Failed"
				duration="12.08s"
				durationms="12080"
				type="test-case"
				rid="b0d08d3589b6000"
				totalerrorcount="1"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="1"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(OpenApp&amp;Login)"
				testcontainerid="61937f4c-9161-4e1c-9d17-78d25c90eb40"
				headertext="TestCase(OpenApp&amp;Login)"
				displayName="TestCase(OpenApp&amp;Login)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
				<activity
					result="Failed"
					duration="12.06s"
					durationms="12064"
					type="test-module"
					rid="a38b1878d332f2e"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					modulename="logIn"
					displayName="logIn"
					moduleid="0fd8dafe-0fee-4dde-842c-5ab594e9145c"
					moduletype="UserCode"
					iteration="1"
					activity-exectype="execute"
					testentry-activity-type="testmodule">
					<varbindings>
					</varbindings>
					<item
						timeRelativeToTestSuiteStartTime="00:12.178"
						timeRelativeToTestModuleStartTime="00:11.968"
						timeWallClock="10:05:28"
						time="00:12.178"
						level="Error"
						category="User"
						errimg="images_smokeTes_2b1a2a21\smokeTes_2b1a2a21_70e3b81b_trace.jpg"
						errthumb="images_smokeTes_2b1a2a21\smokeTes_2b1a2a21_70e3b81b_trace_thumb.jpg">
						<message>
							The test run has been aborted by the user.
						</message>
						<metainfo
							loglvl="Error">
						</metainfo>
					</item>
				</activity>
			</activity>
			<activity
				result="Ignored"
				duration="1ms"
				durationms="1"
				type="test-case"
				rid="1434ef2bf3ceb4dc"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="0"
				totalblockedtestcasecount="1"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="0"
				totalblockedcount="1"
				testcontainername="TestCase(Verification)"
				testcontainerid="f2a26f24-7c5b-403e-9be6-dd76f8db12ea"
				headertext="TestCase(Verification)"
				displayName="TestCase(Verification)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
			</activity>
			<activity
				result="Failed"
				duration="2ms"
				durationms="2"
				type="test-case"
				rid="1326f60a64b85b37"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(addGroups)"
				testcontainerid="13b5b77d-c84b-4f8d-9ccb-a71aa81aa7ff"
				headertext="TestCase(addGroups)"
				displayName="TestCase(addGroups)"
				iteration="0"
				activity-exectype="execute"
				conditionstate="none">
				<errormessage>
					Failed to get rows from data source: Failed to load Excel data. Der Thread wurde abgebrochen.
				</errormessage>
			</activity>
		</activity>
		<item
			timeRelativeToTestSuiteStartTime="00:12.938"
			timeRelativeToTestModuleStartTime="00:12.939"
			timeWallClock="10:05:29"
			time="00:12.938"
			level="Failure"
			category="TestSuite">
			<message>
				Der Thread wurde abgebrochen.
			</message>
			<metainfo
				stacktrace="   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)&#13;&#10;   bei Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.TryRunTestSuite(RunParams rp, TestSuite testSuite)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.&lt;>c__DisplayClass8_1.&lt;RunInternal>b__1()&#13;&#10;   bei Ranorex.Common.Types.OptCombinators.UnwrapOrElse[T](Opt`1 self, Func`1 generator)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
